// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-ui/lib/breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-ui/lib/breadcrumb-item')['default']
    FormFooter: typeof import('./src/components/form-footer/index.vue')['default']
    IconSelect: typeof import('./src/components/icon-select/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    QueryCondition: typeof import('./src/components/query-condition/index.vue')['default']
    RightPanel: typeof import('./src/components/right-panel/index.vue')['default']
    ScrollPane: typeof import('./src/components/tags-view/scroll-pane.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TagsView: typeof import('./src/components/tags-view/index.vue')['default']
  }
}

export { }
