// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadioButton: typeof import('element-ui/lib/radio-button')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTree: typeof import('element-ui/lib/tree')['default']
    FormFooter: typeof import('./src/components/form-footer/index.vue')['default']
    IconSelect: typeof import('./src/components/icon-select/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    QueryCondition: typeof import('./src/components/query-condition/index.vue')['default']
    RightPanel: typeof import('./src/components/right-panel/index.vue')['default']
    ScrollPane: typeof import('./src/components/tags-view/scroll-pane.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TagsView: typeof import('./src/components/tags-view/index.vue')['default']
  }
}

export { }
